sudo pacman -R rubygems                 
sudo pacman -R ruby-rspec
sudo pacman -R ruby-benchmark-ips       
sudo pacman -R ruby-rake-compiler       
sudo pacman -R ruby-rspec-core
sudo pacman -R ruby-benchmark_suite     
sudo pacman -R ruby-rb-fsevent          
sudo pacman -R ruby-rspec-expectations
sudo pacman -R ruby-diff-lcs            
sudo pacman -R ruby-rb-inotify          
sudo pacman -R ruby-rspec-mocks
sudo pacman -R ruby-ffi                 
sudo pacman -R ruby-rdoc                
sudo pacman -R ruby-rspec-support
